### ISSUE TITLE
Desktop wallet not showing balances/info

### ISSUE THREAD

**Issue by Valiant401** [DogepartyXDP/dogewallet-desktop#10]
![Screenshot 2022-11-02 161941](https://user-images.githubusercontent.com/117315462/199598203-685f20b9-bb6e-450d-894f-f826bf88ad20.png)
![Screenshot 2022-11-02 162239](https://user-images.githubusercontent.com/117315462/199598206-79c1f61e-4f6e-4599-af57-0f94a67e68fd.png)

**Comment by jdogresorg** [comment]
I tracked the issue down to requests to api2-api4 xchain servers where /api/network was only handing back burned/earned info and not the network/fee/price info that it should have been.

I have fixed the issue on the XChain servers and wallets should be operating normally again.
