### ISSUE TITLE
Unable to send out coins

### ISSUE THREAD

**Issue by qin1550988682** [DogepartyXDP/dogewallet-desktop#13]
Unable to send out coins

![微信图片_20231215204426](https://github.com/DogepartyXDP/dogewallet-desktop/assets/40701317/0b35ccf0-f30d-4608-9b0c-33198b0818fe)

**Comment by jdogresorg** [comment]
this is not a technical issue with the wallet... this is most likely an issue with your internet connection and not being able to communicate properly with the API servers.

Please join this channel and ask your questions there... https://t.me/freewallet_io
