### ISSUE TITLE
Unable to create dispensers or multisend transactions w/ v 0.9.26

### ISSUE THREAD

**Issue by nutildah** [DogepartyXDP/dogewallet-desktop#14]
I noticed two pretty big issues with the latest Dogewallet release:

1. Create Dispenser function no longer works
- gets stuck on "Generating dogeparty transaction"

2. Multi-send not working
 - gets through Confirm Send
 - gets through signing & broadcast of 1st tx
 - stuck on "Signing second dogeparty transaction"

Thanks for your attention

**Comment by jdogresorg** [comment]
should be fixed in the 0.9.27 release.
