### ISSUE TITLE
Errant asterisk being added to beginning of Description field

### ISSUE THREAD

**Issue by nutildah** [DogepartyXDP/dogewallet-desktop#7]
On occasion (seemingly random) an asterisk will be appended to the beginning of a description, which causes URLs not to be read by xchain. Examples of such instances can be found in the following:

https://dogeparty.xchain.io/asset/DKDOGEBOWL
https://dogeparty.xchain.io/asset/DKDOGEDUEL
https://dogeparty.xchain.io/asset/DOGENICKEZ
https://dogeparty.xchain.io/asset/DOGENICKEY
https://dogeparty.xchain.io/asset/DOGENICKET
https://dogeparty.xchain.io/asset/DOGENICKER
https://dogeparty.xchain.io/asset/DOGENICKEE
https://dogeparty.xchain.io/asset/DOGENICKED
https://dogeparty.xchain.io/asset/DOGENICKEC
https://dogeparty.xchain.io/asset/DOGENICKEB
https://dogeparty.xchain.io/asset/DOGEBLOCKD
https://dogeparty.xchain.io/asset/TWEETONE

For each example, the asterisk is not present in the Issuance tx, yet still appears in the Description field:

https://dogeparty.xchain.io/tx/144498 (Issuance tx for DOGENICKEB)

Example of the issue occurring in a non-URL description:

https://dogeparty.xchain.io/asset/SKBESCROW
https://dogeparty.xchain.io/tx/133158

![image](https://user-images.githubusercontent.com/7720163/189280528-4061f9fa-c6aa-4daf-b91a-34bdd938e49b.png)

**Comment by jdogresorg** [comment]
this should be fixed in the latest dogeparty-lib release (v9.62.0) .. if you find this is still happening, please reopen this issue.
